FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y python3-pip

ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY = host.docker.internal:0.0
ENV export QT_DEBUG_PLUGINS=1
#adding below env variable as a workaround for pyperclip keyError
ENV XDG_SESSION_TYPE=wayland

# Install Python 3, PyQt5
RUN pip3 install --user PyQt5
RUN apt-get update && apt-get install -y python3-pyqt5
RUN pip3 install pycrypto
RUN pip3 install db-sqlite3
RUN pip3 install pyperclip

COPY . /app

WORKDIR "/app"
RUN ls -lrt

CMD python3 main.py
