FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y python3-pip
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN apt-get install -y libxkbcommon-x11-0
RUN apt-get install -y -q libgtk2.0-dev
RUN apt-get install -y -q libgl1-mesa-dev
RUN apt-get install --reinstall libxcb-xinerama0
RUN pip3 install PyQt5
RUN pip3 install pycrypto
RUN pip3 install db-sqlite3

COPY . /app

CMD python3 /app/main.py